name: CI

on:
  pull_request:
    branches: [ master, main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'
        cache: 'npm'

    - name: Install dependencies
      run: |
        rm -f .npmrc
        npm config set registry https://registry.npmjs.org/
        npm install --legacy-peer-deps --no-audit --no-fund --ignore-scripts
        npm run build:core

    - name: Run lint
      run: ng lint

    - name: Run tests
      run: ng test --watch=false --browsers=ChromeHeadless
      continue-on-error: true

    - name: Test results summary
      if: always()
      run: echo "CI pipeline completed. Check individual steps for details."
