name: CI

on:
  pull_request:
    branches: [ master, main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'
        # Disable npm cache to avoid authentication issues
        # cache: 'npm'

    - name: Install dependencies
      run: |
        rm -f .npmrc
        rm -f package-lock.json
        npm config set registry https://registry.npmjs.org/
        npm config delete //registry.npmjs.org/:_authToken || true
        npm whoami || echo "Not logged in to npm (this is expected)"
        npm install --legacy-peer-deps --no-audit --no-fund --ignore-scripts --no-optional
        npm run build:core

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm run test
      continue-on-error: true

    - name: Test results summary
      if: always()
      run: echo "CI pipeline completed. Check individual steps for details."
